# Generated by Django 3.2.11 on 2022-01-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demprjt', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
