# Generated by Django 3.2.11 on 2022-01-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demprjt', '0003_auto_20220115_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image1',
        ),
    ]
